apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica-set
  # these labels are replica set labels
  labels: 
    app: frontend
    tier: web
spec:
# modify replica according to your requirement
  replicas: 3
  selector:
    # replicaset use these labels to find the pods for creating desired number of replicas
    matchLabels:
      app: frontend
      tier: web
  # pod template
  template:
    metadata:
      labels:
        app: frontend
        tier: web
    spec:
      containers:
      - name: nginx
        image: nginx