apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-expense
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-06e13c440c612ddfb
  directoryPerms: "700"
  basePath: "/expense"